spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  thymeleaf:
    prefix: classpath:/templates/   # 模板文件路徑，請確認路徑為 /templates/
    suffix: .html                  # 模板文件的擴展名
    mode: HTML                     # Thymeleaf 模板解析模式
    encoding: UTF-8                # 編碼方式
    cache: false                   # 禁用緩存（建議開發環境下禁用緩存）

server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG
