spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  session:
    #session存储方式
    store-type: redis
    redis:
      host: localhost
      port: 6379
      #redis的超时时间
      timeout: 3000
      #设置会话操作后立即更新到redis中,默认是等服务器请求结束后再将变化的值同步到redis中
      flush-mode: immediate
      pool:
        # 连接池中的最大空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最小空闲连接
        max-wait: -1

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  thymeleaf:
    prefix: classpath:/templates/   # 模板文件路徑，請確認路徑為 /templates/
    suffix: .html                  # 模板文件的擴展名
    mode: HTML                     # Thymeleaf 模板解析模式
    encoding: UTF-8                # 編碼方式
    cache: false                   # 禁用緩存（建議開發環境下禁用緩存）

server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG
